// MOCK: This entire file contains seeded simulation data.
// In production, all exports are replaced by real agent pipeline outputs.

import type { MockStep, ResearchOutputs, BuildOutputs } from '@/types';

// ----------------------------------------------------------------
// Research pipeline step definitions
// MOCK: Replace with real research agent step events streamed from the agent orchestration service.
// ----------------------------------------------------------------
export const MOCK_RESEARCH_STEPS: MockStep[] = [
  { name: 'Identifying target audience',          status: 'pending', durationMs: 3200 },
  { name: 'Scanning competitor landscape',        status: 'pending', durationMs: 4100 },
  { name: 'Analysing pain point signals',         status: 'pending', durationMs: 2800 },
  { name: 'Generating market opportunity report', status: 'pending', durationMs: 5300 },
  { name: 'Compiling go/no-go recommendation',    status: 'pending', durationMs: 2100 },
];

// ----------------------------------------------------------------
// Build pipeline step definitions
// MOCK: Replace with real build agent step events streamed from the agent orchestration service.
// ----------------------------------------------------------------
export const MOCK_BUILD_STEPS: MockStep[] = [
  { name: 'Scaffolding project structure',  status: 'pending', durationMs: 2400 },
  { name: 'Implementing core features',     status: 'pending', durationMs: 18500 },
  { name: 'Writing automated tests',        status: 'pending', durationMs: 6200 },
  { name: 'Deploying to Vercel',            status: 'pending', durationMs: 4800 },
  { name: 'Configuring GitHub repository',  status: 'pending', durationMs: 1900 },
  { name: 'Generating documentation',       status: 'pending', durationMs: 3100 },
];

// ----------------------------------------------------------------
// Research agent outputs (pain point signal, competitor map, recommendation)
// MOCK: Replace with real research agent outputs stored in projects.outputs.research.
// ----------------------------------------------------------------
export const MOCK_RESEARCH_OUTPUTS: ResearchOutputs = {
  painPointSignal:
    'Freelancers consistently report spending 3–5 hours per month chasing unpaid invoices ' +
    'and manually reconciling payments across email, spreadsheets, and bank statements. ' +
    '73% say late payments are their top cash-flow problem, and existing tools like FreshBooks ' +
    'are perceived as “too complex and too expensive” for solo operators. ' +
    'High intent-to-switch detected in freelancer community forums (Reddit r/freelance, Hacker News).',
  competitorMap: [
    {
      name: 'FreshBooks',
      description: 'Full-featured accounting and invoicing SaaS targeting small businesses.',
      weakness: 'Overbuilt for solo freelancers; $17/month minimum plan feels expensive for occasional use.',
    },
    {
      name: 'Wave',
      description: 'Free invoicing and accounting tool with a freemium model.',
      weakness: 'Dated UI; mobile experience is poor; payment processing fees are higher than market average.',
    },
    {
      name: 'PayPal Invoicing',
      description: 'Basic invoice generation bundled with PayPal payments.',
      weakness: 'No client management, no recurring invoices, no reporting; seen as a temporary fix not a real tool.',
    },
  ],
  recommendation: {
    verdict: 'GO',
    rationale:
      'Strong pain signal with validated willingness-to-pay. The freelance invoicing market has clear ' +
      'incumbents with known weaknesses (complexity, cost, poor mobile UX). A focused, mobile-first ' +
      'invoicing tool with a generous free tier and instant payment integration has a credible wedge. ' +
      'Recommended MVP focus: single-client invoice creation, one-click payment link generation, and ' +
      'a simple dashboard showing outstanding vs paid totals. TAM is large; niche entry is achievable.',
  },
};

// ----------------------------------------------------------------
// Build agent outputs — all 6 deliverables
// MOCK: Replace with real build agent outputs stored in projects.outputs.build.
// ----------------------------------------------------------------
export const MOCK_BUILD_OUTPUTS: BuildOutputs = {
  // MOCK: Replace with real research report generated by the research agent.
  researchReport: `## Market Research Report: Freelance Invoice Tracker

**Market Size:** The global freelance platform market is valued at $3.4B and growing at 15% CAGR.
An estimated 59 million Americans freelanced in 2023, with invoicing identified as the #1 administrative
pain point by 68% of respondents in a Freelancers Union survey.

**Target User:** Independent freelancers (designers, developers, writers, consultants) billing 1–20
clients per month. Primary age range: 25–40. Strong mobile usage pattern — 64% manage invoices on phone.

**Validated Pain Points:**
- Manual invoice creation is time-consuming (average 45 minutes/week)
- Chasing late payments causes cash-flow anxiety
- Existing tools are either too expensive or too complex
- No single tool handles creation, sending, reminders, and reconciliation cleanly

**Market Opportunity:** A focused tool priced at $0 (free tier) with a $7/month Pro tier for recurring
invoices and payment reminders has a credible path to 10,000 MAU within 18 months based on organic
SEO and freelancer community distribution.

**Conclusion:** Strong product-market fit signal. Recommend proceeding to MVP build.`,

  // MOCK: Replace with real recommendation generated by the research agent.
  recommendation: `## Product Recommendation: Invoice Tracker for Freelancers

**Verdict: GO**

The research confirms a clear, underserved niche. Existing tools over-serve the target user;
a focused MVP can win on simplicity and price.

**Recommended MVP Scope:**
1. Invoice creation with client name, line items, due date
2. One-click shareable payment link (Stripe integration)
3. Automated payment reminder emails (3-day and 1-day before due)
4. Simple dashboard: Outstanding / Paid / Overdue totals

**Pricing Recommendation:** Free tier (3 active invoices); Pro at $7/month (unlimited).

**Distribution Strategy:** Launch on Product Hunt, post in r/freelance and r/webdev, build SEO
content around “how to invoice clients as a freelancer”. Partner with 2–3 freelancer
communities for beta access.

**Risk:** Wave is free and established. Mitigation: superior mobile UX and payment integration
are the differentiators.`,

  // MOCK: Replace with real requirements document generated by the build agent.
  requirementsDoc: `## Product Requirements: Freelance Invoice Tracker MVP

### User Stories

**Authentication**
- As a freelancer, I want to sign up with my email and password so I can access my invoices securely.
- As a returning user, I want to sign in and see my dashboard immediately.

**Invoice Management**
- As a freelancer, I want to create an invoice by entering a client name, service description,
  amount, and due date so I can bill clients quickly.
- As a freelancer, I want to see all my invoices in a list with status (Draft / Sent / Paid / Overdue)
  so I know where my money is.
- As a freelancer, I want to mark an invoice as paid manually so I can keep my records accurate.

**Payment Collection**
- As a freelancer, I want to generate a shareable payment link for each invoice so my clients
  can pay me via card without friction.
- As a freelancer, I want to receive an email when a client pays so I am notified immediately.

**Reminders**
- As a freelancer, I want the system to automatically send my client a reminder 3 days before
  the invoice is due so I do not have to chase manually.

**Dashboard**
- As a freelancer, I want to see total Outstanding, Paid (this month), and Overdue amounts
  on my dashboard so I can assess my cash flow at a glance.

### Acceptance Criteria (Top 3)
- AC-1: A freelancer can create and send an invoice in under 2 minutes.
- AC-2: A client can pay via the payment link without creating an account.
- AC-3: The dashboard loads in under 1 second on a 4G mobile connection.`,

  // MOCK: Replace with the actual deployed URL produced by the build agent's Vercel deployment step.
  liveMvpUrl: 'https://invoice-tracker-mvp.vercel.app',

  // MOCK: Replace with the actual GitHub repository URL created by the build agent.
  githubLink: 'https://github.com/unicorn-factory/invoice-tracker-mvp',

  // MOCK: Replace with real growth strategy generated by the research agent.
  growthStrategy: `## Growth Strategy: Freelance Invoice Tracker

### Phase 1 — Launch (Months 1–2)
- **Product Hunt launch** on a Tuesday morning (peak traffic day). Target: Top 5 of the day.
- **Community seeding:** Post in r/freelance, r/webdev, Indie Hackers, and relevant Slack/Discord
  groups with a genuine “I built this because I was frustrated” story.
- **Beta outreach:** DM 50 active freelancers on Twitter/LinkedIn; offer 6 months Pro free in
  exchange for public testimonials.

### Phase 2 — SEO & Content (Months 2–6)
- Publish 10 SEO-optimised articles targeting: “invoice template for freelancers”,
  “how to follow up on unpaid invoices”, “best invoicing app for freelancers 2025”.
- Create a free invoice template generator (no sign-up required) as a top-of-funnel tool.
- Target 500 organic monthly visitors by month 4.

### Phase 3 — Paid Conversion (Months 4–12)
- Introduce Pro tier ($7/month) when free users hit the 3-invoice limit.
- Goal: 2% of MAU converting to Pro. At 1,000 MAU that is 20 paying users = $140 MRR.
- Referral program: “Give a friend 1 month Pro, get 1 month Pro” — reduces CAC to near zero.

### North Star Metric
Monthly invoices created. Target: 1,000 invoices/month by month 6.`,
};
