'use client';

// MOCK: Replace deliverables with real build agent outputs stored in projects.outputs column.

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import type { ProjectResponse, BuildOutputs } from '@/types';
import Spinner from '@/components/ui/Spinner';
import ErrorBanner from '@/components/ui/ErrorBanner';
import DeliverableCard from '@/components/DeliverableCard';

export default function DeliverablesPage() {
  const router = useRouter();
  const [build, setBuild] = useState<BuildOutputs | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchProject() {
      const projectId = sessionStorage.getItem('uf_project_id');
      if (!projectId) {
        router.push('/idea');
        return;
      }
      try {
        const res = await fetch(`/api/projects/${projectId}`);
        if (!res.ok) {
          const body = await res.json() as { error?: string };
          setError(body.error ?? 'Failed to load deliverables.');
          setLoading(false);
          return;
        }
        const data = (await res.json()) as ProjectResponse;
        if (data.outputs?.build) {
          setBuild(data.outputs.build);
        } else {
          setError('Deliverables not yet available. Please wait and refresh.');
        }
      } catch {
        setError('Network error loading deliverables.');
      } finally {
        setLoading(false);
      }
    }
    fetchProject();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <Spinner size="lg" />
          <p className="mt-3 text-sm text-gray-500">Loading your deliverables…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-16">
      <div className="mx-auto max-w-4xl">
        <div className="mb-8 text-center">
          <a href="/" className="text-xl font-bold text-indigo-600">
            Unicorn Factory
          </a>
        </div>

        <div className="mb-8 text-center">
          <h1 className="text-3xl font-extrabold text-gray-900">Your MVP is Ready</h1>
          <p className="mt-2 text-gray-500 text-sm">
            Here are all the assets generated by the autonomous pipeline.
          </p>
        </div>

        <ErrorBanner message={error} />

        {build && (
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 mt-6">
            <DeliverableCard
              title="Research Report"
              type="markdown"
              content={build.researchReport}
            />
            <DeliverableCard
              title="Recommendation"
              type="markdown"
              content={build.recommendation}
            />
            <DeliverableCard
              title="Requirements Document"
              type="markdown"
              content={build.requirementsDoc}
            />
            <DeliverableCard
              title="Live MVP URL"
              type="link"
              content={build.liveMvpUrl}
            />
            <DeliverableCard
              title="GitHub Repository"
              type="link"
              content={build.githubLink}
            />
            <DeliverableCard
              title="Growth Strategy"
              type="markdown"
              content={build.growthStrategy}
            />
          </div>
        )}
      </div>
    </div>
  );
}
